version: "3.8"

networks:
  promgraf:
    name: promgraf
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PROMGRAF_SUBNET}
          gateway: ${PROMGRAF_GW}

volumes:
  prometheus_data: 
    driver_opts:
      type: "nfs"
      o: "addr=${PROMGRAF_NFS},rw,vers=4"
      device: ":/sm_nfs/prometheus"
  grafana_data:
     driver_opts:
      type: "nfs"
      o: "addr=${PROMGRAF_NFS},rw,vers=4"
      device: ":/sm_nfs/grafana" 

services:
  # Node Exporter moved to host system 
  #node-exporter:
  #  image: prom/node-exporter:latest
  #  container_name: node-exporter
  #  restart: unless-stopped
  #  volumes:
  #    #- /proc:/host/proc:ro
  #    #- /sys:/host/sys:ro
  #    - /:/rootfs:ro,rslave
  #  command:
  #    #- '--path.procfs=/host/proc'
  #    - '--path.rootfs=/rootfs'
  #    #- '--path.sysfs=/host/sys'
  #    #- '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  #  expose:
  #    - 9100
  #  networks:
  #    - promgraf

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    expose:
      - 8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - promgraf

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    expose:
      - 9090
    volumes:
      - prometheus_data:/prometheus
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=/prometheus/'
      - '--web.route-prefix=/'
    networks:
      - promgraf

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./Grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./Grafana/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./Grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./Grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - promgraf

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      #- ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
      - ./Nginx/ssl/:/etc/nginx/ssl:ro
      - ./Nginx/snippets/:/etc/nginx/conf.d/snippets
    networks:
      - promgraf
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/conf.d
        #- NGINX_RESOLVER=${PROMGRAF_GW}
