apiVersion: 1

deleteDatasources:
  - name: Prometheus
    
datasources:
  - name: Prometheus
    type: prometheus
    uid: PrOmEtHeUs
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
        # exemplarTraceIdDestinations:
        # Field with internal link pointing to data source in Grafana.
        # datasourceUid value can be anything, but it should be unique across all defined data source uids.
        #- datasourceUid: PrOmEtHeUs

